# Generated by Django 5.1.4 on 2025-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Socials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_media", models.CharField(max_length=50)),
                ("link", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="biodata",
            options={
                "verbose_name": "Pesonal Information",
                "verbose_name_plural": "Biographical Data",
            },
        ),
        migrations.AddField(
            model_name="biodata",
            name="experience",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="biodata",
            name="address",
            field=models.CharField(max_length=300),
        ),
    ]
