# Generated by Django 5.1.4 on 2025-01-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bio_data", "0002_socials_alter_biodata_options_biodata_experience_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socials",
            options={"verbose_name_plural": "Socials"},
        ),
        migrations.AlterModelOptions(
            name="technicalexpertise",
            options={"verbose_name_plural": "Techinical Expertise"},
        ),
    ]
