# Generated by Django 5.1.4 on 2025-01-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_data", "0003_alter_socials_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socials",
            name="icon",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
