# Generated by Django 5.1.4 on 2025-01-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bio_data", "0004_socials_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socials",
            name="icon",
        ),
    ]
