# Generated by Django 5.1.4 on 2025-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_data", "0005_remove_socials_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="biodata",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
