# Generated by Django 5.1.4 on 2025-01-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio_data", "0006_biodata_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="biodata",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
