# Generated by Django 5.1.4 on 2025-01-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bio_data", "0011_biodata_resume_biodata_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biodata",
            name="text",
        ),
    ]
