# Generated by Django 5.1.4 on 2025-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bio_data", "0002_socials_alter_biodata_options_biodata_experience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_completed", models.CharField(max_length=7)),
                ("happy_clients", models.CharField(max_length=7)),
                ("success_rate", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="CompletedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("git_link", models.CharField(max_length=1000)),
                ("project_link", models.CharField(max_length=1000)),
                ("tech_used", models.ManyToManyField(to="bio_data.technicalexpertise")),
            ],
        ),
    ]
