# Generated by Django 5.1.4 on 2025-01-11 01:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="completedproject",
            options={"verbose_name_plural": "Completed Projects"},
        ),
        migrations.AlterModelOptions(
            name="credits",
            options={"verbose_name_plural": "Credits"},
        ),
        migrations.AlterField(
            model_name="completedproject",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
