# Generated by Django 5.1.4 on 2025-01-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_data",
            "0002_alter_completedproject_options_alter_credits_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="completedproject",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
